//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labirint_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersSet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdBook { get; set; }
        public string Date { get; set; }
        public Nullable<int> FinalPrice { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual BooksSet BooksSet { get; set; }
        public virtual ClientsSet ClientsSet { get; set; }
    }
}
